### ISSUE TITLE
Bitbloq

### ISSUE THREAD

**Issue by tocalvo** [ashleymcnamara/STEM_Resources_For_Kids#2]
Hi! nice list, can i suggest one website? Its Bitbloq, [bitbloq.org](http://bitbloq.org/#/) 
Bitbloq its a free and OpenSource blocks programming website to program Arduino boards and robots. Available on linux, mac, windows, and chromeOS (Chromebooks). We have an offline version available too. 

Kind regards!
Tom

**Comment by fricikoma** [comment]
Hello. Great list, but I see youcandothecube is a broken link. I would suggest another site CubeSolve.com
